/*
 * sitemap.xml, from the route table.
 *
 * The list of pages lives in one place - `indexedPaths` in data/seo.js,
 * built from the same navigation and legal route tables the app renders
 * from. Generating the sitemap from it rather than keeping a second list by
 * hand is the point: a service added to data/navigation.js appears here on
 * the next build, and a hand-written sitemap that quietly lost a page is the
 * kind of thing nobody notices for a quarter.
 *
 * Written out by scripts/prerender.mjs.
 */

import { absoluteUrl } from "../data/site";
import { indexedPaths, lastModifiedFor } from "../data/seo";

/**
 * Relative importance within this site only. It says nothing to a search
 * engine about how this site compares to any other and most crawlers ignore
 * it, but it costs nothing and records the intended hierarchy: the home
 * page, then the pages the site is built to rank for, then the supporting
 * pages, then the legal documents.
 */
function priorityFor(path) {
  if (path === "/") return "1.0";
  if (path.startsWith("/services")) return "0.9";
  if (path === "/about" || path === "/contact") return "0.8";
  return "0.3";
}

export function sitemapXml() {
  const urls = indexedPaths
    .map((path) =>
      [
        "  <url>",
        `    <loc>${absoluteUrl(path)}</loc>`,
        `    <lastmod>${lastModifiedFor(path)}</lastmod>`,
        `    <priority>${priorityFor(path)}</priority>`,
        "  </url>",
      ].join("\n")
    )
    .join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<!--
  Generated by scripts/prerender.mjs from src/lib/sitemap.js - not by hand.
  Pages come from indexedPaths in src/data/seo.js; the host from siteUrl in
  src/data/site.js; the dates from contentLastUpdated in src/data/seo.js.
-->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`;
}
